### PR TITLE
Kw/time unit

### PR DESCRIPTION
**Pull request by kanitw**
Please merge #157 first.

### CODE REVIEW

**Comment by domoritz** [comment]
Doesn't work. 

screen shot 2015-06-04 at 19 20 37

**Comment by kanitw** [comment]
In what sense?



—
Kanit "Ham" Wongsuphasawat
http://kanitw.yellowpigz.com/ 


Painfully tapped iPhone keyboard--only for you.  Sorry for brevity and typos.

**Comment by domoritz** [comment]
In the sense that it doesn't use the time function in the generated charts.

**Comment by domoritz** [comment]
Oh wait, I haven't updated compass.

**Comment by domoritz** [comment]
My bad, sorry.

**Pull request merged**
