### PR TITLE
Fix test, migrate to mocha, add travis

### LINKED ISSUE #146: Fix tests and add Travis
- copy `vlplot` from ..

### PR DESCRIPTION
**Pull request by kanitw**
**Please merge #154, https://github.com/uwdata/vega-lite-ui/pull/15, and publish vlui 0.7.8 first**

- Fixes #146, #150. 
- also fixes https://github.com/uwdata/vega-lite-ui/issues/14

### CODE REVIEW

**Comment by kanitw** [comment]
@domoritz — FYI, this issue and #157 are now passing!

**Comment by domoritz** [comment]
Yeah, sorry. I started fixing things but the app still didn't work for me (could not find cp.gen). Does everything work for you?

**Comment by kanitw** [comment]
Have you tried (a) `bower unlink` and reinstall, or (b) pull the latest compass and build) ?

**Comment by domoritz** [comment]
Yes. Also, I get the feeling that the order of link is important. 

Still getting errors. 

screen shot 2015-05-28 at 10 21 44

**Comment by kanitw** [comment]
It should be working now.  
Most of the problems are from versioning.

Compass 0.5.4 release was originally broken with missing `compass.js`.  I have just updated the tag.  
Please try
```
git pull 
bower uninstall viscompass
bower clean cache
bower install # to install latest version of datalib and viscompass 
```

Then it should work now.

**Pull request merged**
